name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: |
        echo ${HOME}/.local/bin >> ${GITHUB_PATH}
        sudo make setup

    - name: Build
      run: |
        make configure build

    - name: Lint
      run: |
        make lint
