name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: false

    - name: Setup
      run: |
        echo ${HOME}/.local/bin >> ${GITHUB_PATH}
        make setup

    # - name: Build
    #   run: |
    #     make configure build

    - name: Lint
      run: |
        make lint
